[package]
name = "mv-core"
version = "0.0.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
rand = "0.9.2"
thiserror = "2.0.14"
lazy_static = "1.5.0"
regex = "1.11.1"
indexmap = "2.11.0"
async-trait = "0.1.89"
